sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port:
    database:
    username:
    password:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
